import NavBar from "@/components/NavBar";
import "../styles/main.scss";

import { Inter } from "next/font/google";
import SideBar from "@/components/SideBar";
import SearchForm from "@/components/SearchForm";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({ children }) {
  return (
    <html lang="en ">
      <body class="" className={inter.className}>
        <NavBar />
        <div className="flex">
          <div className="w-[23%] relative ">
            <SideBar />
            <div className="w-[100%] h-[10%] absolute bottom-[10%] text-white text-[10px]  py-[.1rem] px-[2rem] shadow-lg shadow-indigo-500/10 flex flex-col gap-2">
              <h2>• Kampala, Uganda</h2>
              <p className="text-coloR">
                From your IP address • Update location
              </p>
            </div>
          </div>
          <div className=" sm:w-[75%] relative">
            <main className="min-h-screen p-[1rem]">
              {children}
              <div className="w-[73%] h-[14vh] bg-primaryColorbggg  fixed bottom-3 rounded-b-[39px]">
                <SearchForm />
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
