import "../styles/main.scss";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ColAi",
  description: "Generated by create next app",
};
export default async function RootLayout({ children }) {
  return (
    <html lang="en ">
      <body class="relative bg-black" className={inter.className}>
        <main className="">{children}</main>
      </body>
    </html>
  );
}
